questions =  [
    {"id": 0, "question": "Security can only be achieved by maximizing power and hegemony at best.", "effects": {"right": 1}},
    {"id": 1, "question": "Initiator is almost a war winner.", "effects": {"right": 1}},
    {"id": 2, "question": "Alliance potential is overrated.", "effects": {"right": 1}},
    {"id": 3, "question": "If there is such an opportunity it is common for states to attack.", "effects": {"right": 1}},
    {"id": 4, "question": "An external politics cannot be understood without intermal.", "effects": {"right": 1}},
    {"id": 5, "question": "Even the smallest state under the hegemon is safer than the hegemon itself.", "effects": {"right": 1}},
    {"id": 6, "question": "Although the international system pushes states towards hegemony it is more of a threat to security than a protection.", "effects": {"right": 1}},
    {"id": 7, "question": "The hegemon is always defeated how is this secure?", "effects": {"right": 1}},
    {"id": 8, "question": "Obviously the states with the greatest military power will act as they please while the weaker ones will not be able to oppose them.", "effects": {"right": -1}},
    {"id": 9, "question": "The concepts of state power are largely limited to coercion arising from differences in material capabilities.", "effects": {"right": -1}},
    {"id": 10, "question": "The current welfare system should be expanded to further combat inequality.", "effects": {"right": -1}},
    {"id": 11, "question": "No cost can stop a powerful enough state.", "effects": {"right": -1}},
    {"id": 12, "question": "Power largely consists of dependencies; capabilities however great they may be may never be realized.", "effects": {"right": -1}},
    {"id": 13, "question": "The size of the state is not decisive in avoiding coercive influence.", "effects": {"right": -1}},
    {"id": 14, "question": "Military and economic power mean nothing if a state is put over a barrel by the structure of the international system.", "effects": {"right": -1}},
    {"id": 15, "question": "The more interdependent the system is the safer it is.", "effects": {"auth": 1}},
    {"id": 16, "question": "Conflicts can’t be overcome as they are caused by the impulses of human lust for power.", "effects": {"auth": 1}},
    {"id": 17, "question": "A state without resources is nothing.", "effects": {"auth": 1}},
    {"id": 18, "question": "No matter how democratic states are their actions are never directly dictated by the people.", "effects": {"auth": 1}},
    {"id": 19, "question": "Any state as a rational actor can come to conclusions about the unreasonableness of cooperation.", "effects": {"auth": 1}},
    {"id": 20, "question": "Sovereignty can be violated insofar as it is beneficial to everyone.", "effects": {"auth": 1}},
    {"id": 21, "question": "In times of crisis, safety becomes more important than civil liberties.", "effects": {"auth": 1}},
    {"id": 22, "question": "3 factors driving states: motives information capabilities.", "effects": {"auth": 1}},
    {"id": 23, "question": "The most powerful usually means the most informed.", "effects": {"auth": -1}},
    {"id": 24, "question": "National interests must be expanded out of the question.", "effects": {"auth": -1}},
    {"id": 25, "question": "Issues of security and the balance of power are behind the agenda-setting.", "effects": {"auth": -1}},
    {"id": 26, "question": "Nation states can afford to break the law if the situation calls for it.", "effects": {"auth": -1}},
    {"id": 27, "question": "The more polar the world is the less peaceful it is.", "effects": {"auth": -1}},
    {"id": 28, "question": "Political is not always a public but everything that is public must be the object of politics.", "effects": {"auth": -1}},
    {"id": 29, "question": "Social and economic issues are behind the agenda-setting.", "effects": {"auth": -1}},
    {"id": 30, "question": "Any activity of state should be open for debate.", "effects": {"prog": 1}},
    {"id": 31, "question": "The main security issue is to keep security from engulfing all the political debates.", "effects": {"prog": 1}},
    {"id": 32, "question": "The nation-state should be the only unit of analysis.", "effects": {"prog": 1}},
    {"id": 33, "question": "The categories of moral values are not applicable to states.", "effects": {"prog": 1}},
    {"id": 34, "question": "States’ actions determined not by the individuals but the very structure of international politics.", "effects": {"prog": 1}},
    {"id": 35, "question": "We can reduce the degree of anarchy but cannot force states to abandon their interests.", "effects": {"prog": 1}},
    {"id": 36, "question": "The effectiveness of coercion cannot be described as absolute loss for a state.", "effects": {"prog": 1}},
    {"id": 37, "question": "Democracies don't attack each other.", "effects": {"prog": 1}},
    {"id": 38, "question": "States can proceed from their own principles which cannot be reduced to such concepts as power or domination.", "effects": {"prog": -1}},
    {"id": 39, "question": "It is wrong to consider the state in isolation from the individuals.", "effects": {"prog": -1}},
    {"id": 40, "question": "Power is an attribute of states and nothing more.", "effects": {"prog": -1}},
    {"id": 41, "question": "The control of one state over another by means of influence: orders threats or persuasion is the most obvious expression of power.", "effects": {"prog": -1}},
    {"id": 42, "question": "Any state of the international system is the result of a balance of power.", "effects": {"prog": -1}},
    {"id": 43, "question": "If there is something other than the states themselves responsible for their actions then it is useless to study politics.", "effects": {"prog": -1}},
    {"id": 44, "question": "Power can be understood only as we aware of the societies and the patterns they follow.", "effects": {"prog": -1}},
    {"id": 45, "question": "Taming anarchy with the identity of the peace is the best way to achieve it.", "effects": {"prog": -1}}
];
